config/routes.rb
Blogger::Application.routes.draw do
  root 'articles#index'
  resources :articles do
    resources :comments
  end
    resources :tags
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>"}

  def tag_list
    tags.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :articles, through: :taggings

  def to_s
    name
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article.id
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save

    flash.notice = "Article '#{@article.title}' Oh yeah, party time!"

    redirect_to article_path(@article)
  end

  def article_params
    params.require(:article).permit(:title, :body, :tag_list, :image)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    flash.notice = "Article '#{@article.title}' Dead as a door nail!"

    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    flash.notice = "Article '#{@article.title}' Updated!"

    redirect_to article_path(@article)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]

    @comment.save

    redirect_to article_path(@comment.article)
  end

  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    flash.notice = "Tag '#{@tag.name}' Terminated"

    redirect_to tags_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.haml
%article
  %h4 Comment by
  %span
    =comment.author_name
  %p.comment
    =comment.body

  %h5 Posted 
  =distance_of_time_in_words(comment.article.created_at, comment.created_at)
  %p Ago

app/views/articles/_form.html.haml
= form_for(@article, html: {multipart: true}) do |f|
  %ul
    -@article.errors.full_messages.each do |error|
      %li
        =error
  %p
    =f.label :title
    %br
    =f.text_field :title
  %p
    =f.label :body
    %br
    =f.text_area :body
  %p
    =f.label :tag_list
    %br
    =f.text_field :tag_list
  %p
    -if @article.image.exists?
      =image_tag @article.image.url
      %br
    =f.label :image, "Attach New Image"
    %br
    =f.file_field :image
  %p
    =f.submit

app/views/articles/edit.html.haml
%h1 Yeah, baby - fix me.
=render partial: 'form'

app/views/articles/index.html.haml
%h1 All Articles

%ul{:id => "articles"} 
  -@articles.each do |article|
    %li
      =link_to(article.title, article_path(article), class: 'article_title', id: "article_#{article.id}")

%h3
  =link_to("Create a New Article", new_article_path, class: 'new_article')

app/views/articles/new.html.haml
%h1 Create a New Article
=render partial: 'form'

app/views/articles/show.html.haml
%h1
  =@article.title

%p Tags:
-@article.tags.each do |tag|
  =link_to(tag.name, tag_path(tag))

%p
  -if @article.image.exists?
    =image_tag @article.image.url(:medium)

%p
  =@article.body

=render partial: 'comments/form'

%p 
  =link_to("Back to Articles List", articles_path)

%p
  =link_to("Change me, Rearrange me?", edit_article_path(@article))
%br
%p
  =link_to("kill me softly", article_path(@article), method: :delete, data: {confirm: "Seriously? Choose wisely."})

%br
%h3 Oh Shit. Comments. Raise Boom.
%span 
=@article.comments.size
=render partial: 'articles/comment', collection: @article.comments

app/views/comments/_form.html.haml
%h3 Go Ahead. Make my Day.

=form_for [ @article, @comment ] do |f|
  %p 
    =f.label :author_name, "Your Name Here Jerk"
    %br
    =f.text_field :author_name 
  %p
    =f.label :body, "And your dumbass comments here..." 
    %br
    =f.text_area :body 
  %p
    =f.submit 'I Dare You.'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="flash"><%= flash.notice %></p>

<%= yield %>

</body>
</html>

app/views/tags/index.html.haml
%h1 Yes! All of these please.

%ul{:id => "tags"}
  -@tags.each do |tag|
    %li
      =link_to(tag.name, tag_path(tag))

app/views/tags/show.html.haml
%h1 Articles Tagged with 
=@tag.name

%ul
  -@tag.articles.each do |article|
    %li=link_to(article.title, article_path(article))

%h3=link_to("Terminate this Tag", tag_path(@tag), method: :delete, data: {confirm: "Are you sure? There is no going back."})